// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260702182444_addProductTable")]
    partial class addProductTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("ParentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("Name");

                    b.HasIndex("ParentID");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasFilter("[Slug] IS NOT NULL AND [IsDeleted] = 0");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("GroupName");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            ID = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedBy = "SYSTEM",
                            Description = "Product.View permission.",
                            GroupName = "Product",
                            IsDeleted = false,
                            Name = "Product.View"
                        },
                        new
                        {
                            ID = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedBy = "SYSTEM",
                            Description = "Product.Create permission.",
                            GroupName = "Product",
                            IsDeleted = false,
                            Name = "Product.Create"
                        },
                        new
                        {
                            ID = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedBy = "SYSTEM",
                            Description = "Product.Update permission.",
                            GroupName = "Product",
                            IsDeleted = false,
                            Name = "Product.Update"
                        },
                        new
                        {
                            ID = new Guid("10000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedBy = "SYSTEM",
                            Description = "Product.Delete permission.",
                            GroupName = "Product",
                            IsDeleted = false,
                            Name = "Product.Delete"
                        },
                        new
                        {
                            ID = new Guid("20000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedBy = "SYSTEM",
                            Description = "Order.View permission.",
                            GroupName = "Order",
                            IsDeleted = false,
                            Name = "Order.View"
                        },
                        new
                        {
                            ID = new Guid("20000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedBy = "SYSTEM",
                            Description = "Order.Create permission.",
                            GroupName = "Order",
                            IsDeleted = false,
                            Name = "Order.Create"
                        },
                        new
                        {
                            ID = new Guid("20000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedBy = "SYSTEM",
                            Description = "Order.UpdateStatus permission.",
                            GroupName = "Order",
                            IsDeleted = false,
                            Name = "Order.UpdateStatus"
                        },
                        new
                        {
                            ID = new Guid("20000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedBy = "SYSTEM",
                            Description = "Order.Cancel permission.",
                            GroupName = "Order",
                            IsDeleted = false,
                            Name = "Order.Cancel"
                        },
                        new
                        {
                            ID = new Guid("20000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedBy = "SYSTEM",
                            Description = "Order.Approve permission.",
                            GroupName = "Order",
                            IsDeleted = false,
                            Name = "Order.Approve"
                        },
                        new
                        {
                            ID = new Guid("30000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedBy = "SYSTEM",
                            Description = "Inventory.View permission.",
                            GroupName = "Inventory",
                            IsDeleted = false,
                            Name = "Inventory.View"
                        },
                        new
                        {
                            ID = new Guid("30000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedBy = "SYSTEM",
                            Description = "Inventory.Import permission.",
                            GroupName = "Inventory",
                            IsDeleted = false,
                            Name = "Inventory.Import"
                        },
                        new
                        {
                            ID = new Guid("30000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedBy = "SYSTEM",
                            Description = "Inventory.Export permission.",
                            GroupName = "Inventory",
                            IsDeleted = false,
                            Name = "Inventory.Export"
                        },
                        new
                        {
                            ID = new Guid("30000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedBy = "SYSTEM",
                            Description = "Inventory.Adjust permission.",
                            GroupName = "Inventory",
                            IsDeleted = false,
                            Name = "Inventory.Adjust"
                        },
                        new
                        {
                            ID = new Guid("40000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedBy = "SYSTEM",
                            Description = "Report.ViewRevenue permission.",
                            GroupName = "Report",
                            IsDeleted = false,
                            Name = "Report.ViewRevenue"
                        },
                        new
                        {
                            ID = new Guid("40000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedBy = "SYSTEM",
                            Description = "Report.ViewInventory permission.",
                            GroupName = "Report",
                            IsDeleted = false,
                            Name = "Report.ViewInventory"
                        },
                        new
                        {
                            ID = new Guid("50000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedBy = "SYSTEM",
                            Description = "User.View permission.",
                            GroupName = "User",
                            IsDeleted = false,
                            Name = "User.View"
                        },
                        new
                        {
                            ID = new Guid("50000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedBy = "SYSTEM",
                            Description = "User.Create permission.",
                            GroupName = "User",
                            IsDeleted = false,
                            Name = "User.Create"
                        },
                        new
                        {
                            ID = new Guid("50000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedBy = "SYSTEM",
                            Description = "User.Update permission.",
                            GroupName = "User",
                            IsDeleted = false,
                            Name = "User.Update"
                        },
                        new
                        {
                            ID = new Guid("50000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedBy = "SYSTEM",
                            Description = "User.AssignRole permission.",
                            GroupName = "User",
                            IsDeleted = false,
                            Name = "User.AssignRole"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("CategoryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(50000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ReasonRevoked")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserID");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSystemRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            ID = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedBy = "SYSTEM",
                            Description = "System administrator with full access.",
                            IsDeleted = false,
                            IsSystemRole = true,
                            Name = "Admin"
                        },
                        new
                        {
                            ID = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedBy = "SYSTEM",
                            Description = "Manager role for product, order, inventory and report operations.",
                            IsDeleted = false,
                            IsSystemRole = true,
                            Name = "Manager"
                        },
                        new
                        {
                            ID = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedBy = "SYSTEM",
                            Description = "Staff role for basic back-office operations.",
                            IsDeleted = false,
                            IsSystemRole = true,
                            Name = "Staff"
                        },
                        new
                        {
                            ID = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedBy = "SYSTEM",
                            Description = "Default customer role.",
                            IsDeleted = false,
                            IsSystemRole = true,
                            Name = "Customer"
                        });
                });

            modelBuilder.Entity("Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleID", "PermissionID");

                    b.HasIndex("PermissionID");

                    b.ToTable("RolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleID = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionID = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleID = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionID = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleID = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionID = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RoleID = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionID = new Guid("10000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RoleID = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionID = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleID = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionID = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleID = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionID = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RoleID = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionID = new Guid("20000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RoleID = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionID = new Guid("20000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            RoleID = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionID = new Guid("30000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleID = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionID = new Guid("30000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleID = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionID = new Guid("30000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RoleID = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionID = new Guid("30000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RoleID = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionID = new Guid("40000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleID = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionID = new Guid("40000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleID = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionID = new Guid("50000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleID = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionID = new Guid("50000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleID = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionID = new Guid("50000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RoleID = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionID = new Guid("50000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RoleID = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermissionID = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleID = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermissionID = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleID = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermissionID = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RoleID = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermissionID = new Guid("10000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RoleID = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermissionID = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleID = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermissionID = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleID = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermissionID = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RoleID = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermissionID = new Guid("20000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RoleID = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermissionID = new Guid("20000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            RoleID = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermissionID = new Guid("30000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleID = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermissionID = new Guid("30000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleID = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermissionID = new Guid("30000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RoleID = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermissionID = new Guid("30000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RoleID = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermissionID = new Guid("40000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleID = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermissionID = new Guid("40000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleID = new Guid("33333333-3333-3333-3333-333333333333"),
                            PermissionID = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleID = new Guid("33333333-3333-3333-3333-333333333333"),
                            PermissionID = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleID = new Guid("33333333-3333-3333-3333-333333333333"),
                            PermissionID = new Guid("30000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleID = new Guid("44444444-4444-4444-4444-444444444444"),
                            PermissionID = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleID = new Guid("44444444-4444-4444-4444-444444444444"),
                            PermissionID = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleID = new Guid("44444444-4444-4444-4444-444444444444"),
                            PermissionID = new Guid("20000000-0000-0000-0000-000000000004")
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserID", "RoleID");

                    b.HasIndex("RoleID");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.HasOne("Domain.Entities.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.HasOne("Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
